sonar.projectKey=Leonardo_Chocce_t1
sonar.projectName=Leonardo_Chocce_t1
sonar.sources=producer,consumer,config
sonar.exclusions=.venv/**, .scannerwork/**
sonar.host.url=https://sonarqube.ingsoftware.lat/

# CONFIGURACIÓN DE PRUEBAS Y COBERTURA
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.10
