sonar.projectKey=Leonardo_Chocce_t1
sonar.projectName=Leonardo_Chocce_t1
sonar.sources=producer,consumer,config
sonar.exclusions=.venv/**,.scannerwork/**,**/main_*.py,**/__init__.py,producer/adapters/rabbitmq_publisher_adapter.py,consumer/adapters/rabbitmq_consumer_adapter.py,consumer/ports/*.py,producer/ports/*.py
sonar.host.url=https://sonarqube.ingsoftware.lat/

sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.10
